///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 
using System;
using System.Collections.Generic;
using MoonSharp.Interpreter;

using UniRx;
using System.Runtime.Serialization;

namespace Service.Scripting {
    
    public class Events {
        
        [DataContract(IsReference = true)]
        public class WriteToScriptingConsole {
           [DataMember] public string text;

        }

        [DataContract(IsReference = true)]
        public class ScriptingConsoleOpened {

        }
        
    }
}
///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 
