///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 

using System;
using System.Collections.Generic;
using MoonSharp.Interpreter;

using static Service.Scripting.Events;
using UniRx;
using Zenject;
using System.Runtime.Serialization;

namespace Service.Scripting {
    public interface IScriptingService {



					void OpenScriptingConsole();


					void CloseScriptingConsole();


					void ToggleScriptingConsole();


					Script GetMainScript();


					bool IsScriptingConsoleVisible();


					string ExecuteStringOnMainScript(string luaCode);

	}



}
///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 
