///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 

using System;
using System.Collections.Generic;
using MoonSharp.Interpreter;

using static Service.Scripting.Events;
using UniRx;
using Zenject;
using System.Runtime.Serialization;

namespace Service.Scripting {
    public interface IScriptingService {



					void OpenScriptingConsole();


					void CloseScriptingConsole();


					void ToggleScriptingConsole();


					Script GetMainScript();


					bool IsScriptingConsoleVisible();


		/// <summary>
        /// Execute a string into the default-lua-context 
        /// <param name="luaCode"></param>
 /// </summary>
        

					string ExecuteStringOnMainScript(string luaCode);


		/// <summary>
        /// Load a script into the default lua-context 
        /// <param name="fileName"></param>
 /// </summary>
        

					string ExecuteFileToMainScript(string fileName);


		/// <summary>
        /// Generates a list of possible proposals 
        /// <param name="currentInput"></param>
        /// <param name="cursorPos"></param>
 /// </summary>
        

					Proposal AutocompleteProposals(string currentInput,int cursorPos);


		/// <summary>
        /// Output to console 
        /// <param name="text"></param>
 /// </summary>
        

					void WriteToScriptingConsole(string text);

	}



}
///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 
