///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 
/*block:using*/using /*name:name*/System/*endname*/;
/*endblock:using*/
using UniRx;
using System.Runtime.Serialization;

namespace /*name:namespace*/Service.GeneratorPrototype/*endname*/ {
    
    public class Events {
        /*block:event*/
        [DataContract(IsReference = true)]
        public class /*name:eventName*/DidPrototype/*endname*/ {
/*block:field*/           [DataMember] /*name:scope*/public/*endname*/ /*name:type*/string/*endname*/ /*name:name*/settings/*endname*//*block:valueBlock*/= /*name:value*/"value"/*endname*//*endblock:valueBlock*/;
/*endblock:field*/
        }
/*endblock:event*/        
    }
}
///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 