// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Serial
{

using global::System;
using global::FlatBuffers;

public struct FBComponent : IFlatbufferObject
{
  private Table __p;
public int pos { get { return __p.bb_pos; } }  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static FBComponent GetRootAsFBComponent(ByteBuffer _bb) { return GetRootAsFBComponent(_bb, new FBComponent()); }
  public static FBComponent GetRootAsFBComponent(ByteBuffer _bb, FBComponent obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FBComponent __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FBUID? Id { get { int o = __p.__offset(4); return o != 0 ? (FBUID?)(new FBUID()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public FBUID? Entity { get { int o = __p.__offset(6); return o != 0 ? (FBUID?)(new FBUID()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public bool WasConstructed { get { int o = __p.__offset(8); return o != 0 ? 0!=__p.bb.Get(o + __p.bb_pos) : (bool)false; } }

  public static Offset<FBComponent> CreateFBComponent(FlatBufferBuilder builder,
      Offset<FBUID> idOffset = default(Offset<FBUID>),
      Offset<FBUID> entityOffset = default(Offset<FBUID>),
      bool wasConstructed = false) {
    builder.StartObject(3);
    FBComponent.AddEntity(builder, entityOffset);
    FBComponent.AddId(builder, idOffset);
    FBComponent.AddWasConstructed(builder, wasConstructed);
    return FBComponent.EndFBComponent(builder);
  }

  public static void StartFBComponent(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddId(FlatBufferBuilder builder, Offset<FBUID> idOffset) { builder.AddOffset(0, idOffset.Value, 0); }
  public static void AddEntity(FlatBufferBuilder builder, Offset<FBUID> entityOffset) { builder.AddOffset(1, entityOffset.Value, 0); }
  public static void AddWasConstructed(FlatBufferBuilder builder, bool wasConstructed) { builder.AddBool(2, wasConstructed, false); }
  public static Offset<FBComponent> EndFBComponent(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<FBComponent>(o);
  }
};


}
