// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Serial
{

using global::System;
using global::FlatBuffers;

public struct FBUID : IFlatbufferObject
{
  private Table __p;
public int pos { get { return __p.bb_pos; } }  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static FBUID GetRootAsFBUID(ByteBuffer _bb) { return GetRootAsFBUID(_bb, new FBUID()); }
  public static FBUID GetRootAsFBUID(ByteBuffer _bb, FBUID obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FBUID __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Id { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<FBUID> CreateFBUID(FlatBufferBuilder builder,
      int id = 0) {
    builder.StartObject(1);
    FBUID.AddId(builder, id);
    return FBUID.EndFBUID(builder);
  }

  public static void StartFBUID(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddId(FlatBufferBuilder builder, int id) { builder.AddInt(0, id, 0); }
  public static Offset<FBUID> EndFBUID(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<FBUID>(o);
  }
};


}
