// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Serial
{

using global::System;
using global::FlatBuffers;

public struct FBVector3 : IFlatbufferObject
{
  private Table __p;
public int pos { get { return __p.bb_pos; } }  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static FBVector3 GetRootAsFBVector3(ByteBuffer _bb) { return GetRootAsFBVector3(_bb, new FBVector3()); }
  public static FBVector3 GetRootAsFBVector3(ByteBuffer _bb, FBVector3 obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public FBVector3 __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public float X { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Y { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Z { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<FBVector3> CreateFBVector3(FlatBufferBuilder builder,
      float x = 0.0f,
      float y = 0.0f,
      float z = 0.0f) {
    builder.StartObject(3);
    FBVector3.AddZ(builder, z);
    FBVector3.AddY(builder, y);
    FBVector3.AddX(builder, x);
    return FBVector3.EndFBVector3(builder);
  }

  public static void StartFBVector3(FlatBufferBuilder builder) { builder.StartObject(3); }
  public static void AddX(FlatBufferBuilder builder, float x) { builder.AddFloat(0, x, 0.0f); }
  public static void AddY(FlatBufferBuilder builder, float y) { builder.AddFloat(1, y, 0.0f); }
  public static void AddZ(FlatBufferBuilder builder, float z) { builder.AddFloat(2, z, 0.0f); }
  public static Offset<FBVector3> EndFBVector3(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<FBVector3>(o);
  }
};


}
