///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 

using System;
using System.Collections.Generic;
using MoonSharp.Interpreter;

using static Service.FileSystem.Events;
using UniRx;
using Zenject;
using System.Runtime.Serialization;

namespace Service.FileSystem {
    public interface IFileSystemService {



		/// <summary>
        /// Get path as string for given domain 
        /// <param name="domain"></param>
 /// </summary>
        

					string GetPath(FSDomain domain);


		/// <summary>
        /// Write string to file 
        /// <param name="pathToFile"></param>
        /// <param name="data"></param>
 /// </summary>
        

					bool WriteStringToFile(string pathToFile,string data);


		/// <summary>
        /// Write string to file at domain 
        /// <param name="domain"></param>
        /// <param name="relativePathToFile"></param>
        /// <param name="data"></param>
 /// </summary>
        

					bool WriteStringToFileAtDomain(FSDomain domain,string relativePathToFile,string data);


		/// <summary>
        /// Load file as string 
        /// <param name="pathToFile"></param>
 /// </summary>
        

					string LoadFileAsString(string pathToFile);


		/// <summary>
        /// Load file as string from domain 
        /// <param name="domain"></param>
        /// <param name="relativePathToFile"></param>
 /// </summary>
        

					string LoadFileAsStringAtDomain(FSDomain domain,string relativePathToFile);

	}


    public enum FSDomain {
        ScriptingOutput,RuntimeAssets
        
    }


}
///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 
