///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 
using System;
using System.Collections.Generic;
using MoonSharp.Interpreter;

using UniRx;
using System.Runtime.Serialization;

namespace Service.GameStateService {
    
    public class Events {
        
        [DataContract(IsReference = true)]
        public class GameStateStatusChange {
           [DataMember] public GameState gameState;
           [DataMember] public GSStatus fromStatus;
           [DataMember] public GSStatus toStatus;

        }
        
    }
}
///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 
