///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 

using System;
using System.Collections.Generic;
using MoonSharp.Interpreter;

using static Service.MemoryBrowserService.Events;
using UniRx;
using Zenject;
using System.Runtime.Serialization;

namespace Service.MemoryBrowserService {
    public interface IMemoryBrowserService {



					bool IsSimpleType(object obj);


					MemoryBrowser CreateMemoryBrowser(string id,object root);


					MemoryBrowser GetBrowser(string id);

	}



    [DataContract(IsReference = true)]
    public class Watch {
        [DataMember]public string name ;
        [DataMember]public object value ;

    }

}
///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 
