///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 

using System;

using static Service.AsyncManager.Events;
using UniRx;
using Zenject;
using System.Runtime.Serialization;
using System.Collections.Generic;

namespace Service.AsyncManager {
    public interface IAsyncManager {



					AsyncFuture AddToMainThread(Action act,bool global=false);


					AsyncFuture AddToWorkerThread(Action act,Action onFinished,bool global=false);


					AsyncFuture Call(Action act,bool usingCoroutine,bool global=false);


					void DisposeThreads(bool onlyNonGlobals=false);

	}



}
///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 
