///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 

using System;

using static Service.AsyncManager.Events;
using UniRx;
using Zenject;
using System.Runtime.Serialization;

namespace Service.AsyncManager {
    public interface IAsyncManager {



					AsyncFuture AddToMainThread(Action act);


					AsyncFuture AddToWorkerThread(Action act,Action onFinished);


					AsyncFuture Call(Action act,bool usingCoroutine);


					void DisposeThreads();

	}



}
///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 
