///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 

using System.Collections.Generic;
using MoonSharp.Interpreter;
using Service.GameStateService;

using System;
using static Service.TimeService.Events;
using System.Runtime.Serialization;
using FlatBuffers;
using Service.Serializer;
using System.Linq;

namespace Service.TimeService {
    public interface ITimeService : IFBSerializable, IService {




		/// <summary>
        /// Adds a timer in the global update-method and calls the callback n-times (or infinite till application end) 
        /// <param name="interval"></param>
        /// <param name="callback"></param>
        /// <param name="repeatTimes"></param>
        /// <param name="info"></param>
 /// </summary>
        

					TimerElement CreateGlobalTimer(float interval,Action callback,int repeatTimes,string info="");
    


					void RemoveGlobalTimer(TimerElement timer);
    


	}


    
    [System.Serializable]
    public  class TimerElement: DefaultSerializable2
    {

        private ExtendedTable ser2table = ExtendedTable.NULL;

        public new ExtendedTable Ser2Table => ser2table;

        public new bool Ser2IsDirty { get; set; } // TODO. Is dirty should be some kind of virtual

        public new bool Ser2HasOffset => !ser2table.IsNULL();

        public new int Ser2Offset => ser2table.offset;

        public virtual void Ser2Deserialize(DeserializationContext ctx) {
            int offset = ctx.bb.Length - ctx.bb.GetInt(ctx.bb.Position) + ctx.bb.Position;
            Ser2Deserialize(offset, ctx);
        }

        public virtual int Ser2Serialize(SerializationContext ctx) {
            if (!Ser2HasOffset) {
                Ser2CreateTable(ctx, ctx.builder);
            } else {
                Ser2UpdateTable(ctx, ctx.builder);
            }
            return base.ser2table.offset;
        }

        public TimerElement() { }
        
        /// <summary>
        /// 
        /// </summary>
        
        public string info ;
        
        /// <summary>
        /// 
        /// </summary>
        
        public float timeLeft ;
        
        /// <summary>
        /// 
        /// </summary>
        
        public float interval ;
        
        /// <summary>
        /// 
        /// </summary>
        
        public int repeatTimes ;
        
        /// <summary>
        /// 
        /// </summary>
        
        public Action timerCallback ;
        
        
        
        /// <summary>
        /// Default constructor
        /// </summary>
        
    }

    
}
///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 
