///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 
using System;
using System.Collections.Generic;
using MoonSharp.Interpreter;

using UniRx;
using System.Runtime.Serialization;

namespace Service.DevUIService {
    
    public class Events {
        
        [DataContract(IsReference = true)]
        public class NewUIElement {
           [DataMember] public DevUIElement elem;
           [DataMember] public DevUIView view;
           [DataMember] public bool inEditMode;

        }
        
    }
}
///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 
