///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 

using System;
using System.Collections.Generic;
using MoonSharp.Interpreter;

using static Service.DevUIService.Events;
using UniRx;
using Zenject;
using System.Runtime.Serialization;

namespace Service.DevUIService {
    public interface IDevUIService {



		/// <summary>
        /// Get ReaciveDictionar of all views 
 /// </summary>
        

					ReactiveDictionary<string,DevUIView> GetRxViews();


		/// <summary>
        /// Add/Create view with name 
        /// <param name="viewName"></param>
 /// </summary>
        

					DevUIView AddView(string viewName);


		/// <summary>
        /// Get a view by name 
        /// <param name="viewName"></param>
 /// </summary>
        

					DevUIView GetView(string viewName);


		/// <summary>
        /// Check if view already exists 
        /// <param name="viewName"></param>
 /// </summary>
        

					bool ViewNameExists(string viewName);

	}



}
///////////////////////////////////////////////////////////////////////
//
// WARNING: THIS FILE IS AUTOGENERATED! DO NOT CHANGE IT
//
////////////////////////////////////////////////////////////////////// 
